# Generated by Django 2.2.5 on 2019-09-10 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Round',
        ),
        migrations.RemoveField(
            model_name='course',
            name='par',
        ),
        migrations.AddField(
            model_name='hole',
            name='yards',
            field=models.IntegerField(default=350),
        ),
        migrations.AddField(
            model_name='score',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='score',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
