# Generated by Django 2.2.5 on 2019-09-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='playing_handicap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
