# Generated by Django 2.2.5 on 2019-09-06 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0002_auto_20190905_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='played_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
