# Generated by Django 2.2.5 on 2019-09-10 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0002_auto_20190910_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='stroke_index',
            field=models.IntegerField(default=9, validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(1)]),
        ),
    ]
