# Generated by Django 2.2.5 on 2019-09-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_auto_20190910_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='handicap',
            field=models.FloatField(null=True),
        ),
    ]
